-- begin KDP_DEPARTMENT
alter table KDP_DEPARTMENT add constraint FK_KDP_DEPARTMENT_ON_ORGANIZATION foreign key (ORGANIZATION_ID) references KDP_ORGANIZATIONS(ID)^
create unique index IDX_KDP_DEPARTMENT_UNIQ_CODE on KDP_DEPARTMENT (CODE)^
create index IDX_KDP_DEPARTMENT_ON_ORGANIZATION on KDP_DEPARTMENT (ORGANIZATION_ID)^
-- end KDP_DEPARTMENT
-- begin KDP_CONTRACT
create unique index IDX_KDP_CONTRACT_UNIQ_NUMBER on KDP_CONTRACT (NUMBER)^
create unique index IDX_KDP_CONTRACT_UNIQ_STATE on KDP_CONTRACT (STATE)^
-- end KDP_CONTRACT
