alter table KDP_EMPLOYEE add constraint FK_KDP_EMPLOYEE_ON_COMPANY foreign key (COMPANY_ID) references KDP_COMPANY(ID);
create unique index IDX_KDP_EMPLOYEE_UNIQ_TAB_NUMBER on KDP_EMPLOYEE (TAB_NUMBER);
create index IDX_KDP_EMPLOYEE_ON_COMPANY on KDP_EMPLOYEE (COMPANY_ID);
