alter table KDP_DEPARTMENTS add constraint FK_KDP_DEPARTMENTS_ON_MANAGER_ID foreign key (MANAGER_ID_ID) references SEC_USER(ID);
create index IDX_KDP_DEPARTMENTS_ON_MANAGER_ID on KDP_DEPARTMENTS (MANAGER_ID_ID);
