alter table KDP_DEPARTMENTS add constraint FK_KDP_DEPARTMENTS_ON_ORGANIZATION foreign key (ORGANIZATION_ID) references KDP_ORGANIZATIONS(ID);
create index IDX_KDP_DEPARTMENTS_ON_ORGANIZATION on KDP_DEPARTMENTS (ORGANIZATION_ID);
