alter table KDP_VACATION_REQUEST add constraint FK_KDP_VACATION_REQUEST_ON_COORDINATOR foreign key (COORDINATOR_ID) references KDP_EMPLOYEES(ID);
create index IDX_KDP_VACATION_REQUEST_ON_COORDINATOR on KDP_VACATION_REQUEST (COORDINATOR_ID);
