alter table KDP_POSITION add constraint FK_KDP_POSITION_ON_ORGANIZATIONS_ID foreign key (ORGANIZATIONS_ID_ID) references KDP_ORGANIZATIONS(ID);
create index IDX_KDP_POSITION_ON_ORGANIZATIONS_ID on KDP_POSITION (ORGANIZATIONS_ID_ID);
