alter table KDP_DEPARTMENT add constraint FK_KDP_DEPARTMENT_ON_MANAGER_ID foreign key (MANAGER_ID_ID) references SEC_USER(ID);
create index IDX_KDP_DEPARTMENT_ON_MANAGER_ID on KDP_DEPARTMENT (MANAGER_ID_ID);
