alter table KDP_VACATION_REQUEST alter column DEPARTMENTS_ID rename to DEPARTMENTS_ID__U95991 ^
drop index IDX_KDP_VACATION_REQUEST_ON_DEPARTMENTS ;
alter table KDP_VACATION_REQUEST add column DEPARTMENTS_ID varchar(36) ;
