alter table KDP_DEPARTMENT add constraint FK_KDP_DEPARTMENT_ON_APPROVAL_MANAGER foreign key (APPROVAL_MANAGER_ID) references SEC_USER(ID);
create index IDX_KDP_DEPARTMENT_ON_APPROVAL_MANAGER on KDP_DEPARTMENT (APPROVAL_MANAGER_ID);
