create table KDP_VACATION_REQUEST (
    ID varchar(36) not null,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    --
    APPLICATION_NUMBER integer not null,
    APPLICATION_DATE date,
    EMPLOYEES_ID varchar(36) not null,
    COMPANY_ID varchar(36) not null,
    DEPARTMENTS_ID varchar(36),
    POSITION_ID varchar(36),
    COORDINATOR_ID varchar(36) not null,
    VACATION_TYPE_ID varchar(36),
    REMAINING_VACATION_DAYS integer,
    DATE_FROM date,
    DATE_BY date,
    VACATION_DAYS integer,
    INFORMATION_FOR_CONSULTATIONS varchar(255),
    NOTE varchar(255),
    CONSENT_TO_BILLING boolean,
    document_ID varchar(36),
    INITIATOR_ID varchar(36),
    UPLOAD_TO_1C boolean,
    STATUS varchar(255),
    COMMENT varchar(255),
    --
    primary key (ID)
);