alter table KDP_VACATION_REQUEST add constraint FK_KDP_VACATION_REQUEST_ON_DOCUMENT foreign key (DOCUMENT_ID) references SYS_FILE(ID);
create index IDX_KDP_VACATION_REQUEST_ON_DOCUMENT on KDP_VACATION_REQUEST (DOCUMENT_ID);
