alter table KDP_POSITION add constraint FK_KDP_POSITION_ON_COMPANY_ID foreign key (COMPANY_ID_ID) references KDP_ORGANIZATIONS(ID);
create index IDX_KDP_POSITION_ON_COMPANY_ID on KDP_POSITION (COMPANY_ID_ID);
