alter table KDP_ACCESS_REQUEST add constraint FK_KDP_ACCESS_REQUEST_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references KDP_EMPLOYEES(ID);
alter table KDP_ACCESS_REQUEST add constraint FK_KDP_ACCESS_REQUEST_ON_COMPANY foreign key (COMPANY_ID) references KDP_ORGANIZATIONS(ID);
alter table KDP_ACCESS_REQUEST add constraint FK_KDP_ACCESS_REQUEST_ON_MANAGER foreign key (MANAGER_ID) references KDP_EMPLOYEES(ID);
alter table KDP_ACCESS_REQUEST add constraint FK_KDP_ACCESS_REQUEST_ON_PROC_INSTANCE foreign key (PROC_INSTANCE) references BPM_PROC_INSTANCE(ID);
create index IDX_KDP_ACCESS_REQUEST_ON_EMPLOYEE on KDP_ACCESS_REQUEST (EMPLOYEE_ID);
create index IDX_KDP_ACCESS_REQUEST_ON_COMPANY on KDP_ACCESS_REQUEST (COMPANY_ID);
create index IDX_KDP_ACCESS_REQUEST_ON_MANAGER on KDP_ACCESS_REQUEST (MANAGER_ID);
create index IDX_KDP_ACCESS_REQUEST_ON_PROC_INSTANCE on KDP_ACCESS_REQUEST (PROC_INSTANCE);
