alter table KDP_BUSINESS_TRIP add constraint FK_KDP_BUSINESS_TRIP_ON_POSITION foreign key (POSITION_ID) references KDP_POSITION(ID);
create index IDX_KDP_BUSINESS_TRIP_ON_POSITION on KDP_BUSINESS_TRIP (POSITION_ID);
