alter table KDP_BUSINESS_TRIP add constraint FK_KDP_BUSINESS_TRIP_ON_PROC_INSTANCE foreign key (PROC_INSTANCE_ID) references BPM_PROC_INSTANCE(ID);
create index IDX_KDP_BUSINESS_TRIP_ON_PROC_INSTANCE on KDP_BUSINESS_TRIP (PROC_INSTANCE_ID);
