alter table KDP_EMPLOYEES alter column SURNAME_UA set data type varchar(255) ;
alter table KDP_EMPLOYEES alter column SURNAME_UA drop not null ;
alter table KDP_EMPLOYEES alter column NAME_UA set data type varchar(255) ;
alter table KDP_EMPLOYEES alter column NAME_UA drop not null ;
alter table KDP_EMPLOYEES alter column MIDDLE_NAME_UA set data type varchar(255) ;
alter table KDP_EMPLOYEES alter column MIDDLE_NAME_UA drop not null ;
alter table KDP_EMPLOYEES alter column SURNAME_RU set data type varchar(255) ;
alter table KDP_EMPLOYEES alter column NAME_RU set data type varchar(255) ;
alter table KDP_EMPLOYEES alter column MIDDLE_NAME_RU set data type varchar(255) ;
alter table KDP_EMPLOYEES alter column SURNAME_EN set data type varchar(255) ;
alter table KDP_EMPLOYEES alter column NAME_EN set data type varchar(255) ;
alter table KDP_EMPLOYEES alter column MIDDLE_NAME_EN set data type varchar(255) ;
alter table KDP_EMPLOYEES alter column WORK_EMAIL set data type varchar(255) ;
alter table KDP_EMPLOYEES alter column OTHER_EMAIL set data type varchar(255) ;
alter table KDP_EMPLOYEES alter column WORK_PHONE set data type varchar(255) ;
alter table KDP_EMPLOYEES alter column MOBILE_PHONE set data type varchar(255) ;
alter table KDP_EMPLOYEES alter column LOGIN_NAME set data type varchar(255) ;
