alter table KDP_BUSINESS_TRIP add constraint FK_KDP_BUSINESS_TRIP_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references KDP_EMPLOYEES(ID);
create index IDX_KDP_BUSINESS_TRIP_ON_DEPARTMENT on KDP_BUSINESS_TRIP (DEPARTMENT_ID);
