alter table KDP_VACATION_FILES add constraint FK_KDP_VACATION_FILES_ON_DOCUMENT foreign key (DOCUMENT_ID) references SYS_FILE(ID);
alter table KDP_VACATION_FILES add constraint FK_KDP_VACATION_FILES_ON_VACATION foreign key (VACATION_ID) references KDP_BUSINESS_TRIP(ID);
alter table KDP_VACATION_FILES add constraint FK_KDP_VACATION_FILES_ON_AUTHOR foreign key (AUTHOR_ID) references KDP_EMPLOYEES(ID);
create index IDX_KDP_VACATION_FILES_ON_DOCUMENT on KDP_VACATION_FILES (DOCUMENT_ID);
create index IDX_KDP_VACATION_FILES_ON_VACATION on KDP_VACATION_FILES (VACATION_ID);
create index IDX_KDP_VACATION_FILES_ON_AUTHOR on KDP_VACATION_FILES (AUTHOR_ID);
