alter table KDP_ADDRESSING add constraint FK_KDP_ADDRESSING_ON_PROC_DEFINITION foreign key (PROC_DEFINITION_ID) references BPM_PROC_DEFINITION(ID);
alter table KDP_ADDRESSING add constraint FK_KDP_ADDRESSING_ON_COMPANY foreign key (COMPANY_ID) references KDP_ORGANIZATIONS(ID);
create index IDX_KDP_ADDRESSING_ON_PROC_DEFINITION on KDP_ADDRESSING (PROC_DEFINITION_ID);
create index IDX_KDP_ADDRESSING_ON_COMPANY on KDP_ADDRESSING (COMPANY_ID);
