alter table KDP_VACATION_REQUEST add constraint FK_KDP_VACATION_REQUEST_ON_INITIATOR foreign key (INITIATOR_ID) references KDP_EMPLOYEES(ID);
create index IDX_KDP_VACATION_REQUEST_ON_INITIATOR on KDP_VACATION_REQUEST (INITIATOR_ID);
