alter table KDP_VACATION_BALANCE add constraint FK_KDP_VACATION_BALANCE_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references KDP_EMPLOYEES(ID);
alter table KDP_VACATION_BALANCE add constraint FK_KDP_VACATION_BALANCE_ON_VACATION_TYPE foreign key (VACATION_TYPE_ID) references KDP_VACATION_TYPE(ID);
create index IDX_KDP_VACATION_BALANCE_ON_EMPLOYEE on KDP_VACATION_BALANCE (EMPLOYEE_ID);
create index IDX_KDP_VACATION_BALANCE_ON_VACATION_TYPE on KDP_VACATION_BALANCE (VACATION_TYPE_ID);
