alter table KDP_EMPLOYEES add constraint FK_KDP_EMPLOYEES_ON_APPROVAL_MANAGER foreign key (APPROVAL_MANAGER_ID) references KDP_EMPLOYEES(ID);
create index IDX_KDP_EMPLOYEES_ON_APPROVAL_MANAGER on KDP_EMPLOYEES (APPROVAL_MANAGER_ID);
